---

Resources:

  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: fargate-demo2

  RootRole:
    Type: "AWS::IAM::Role"
    Description: A baseline IAM role for ECS Task Execution
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: "/"
      RoleName: fargateDemoEcsTaskExecutionRole

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 0.5GB
      ContainerDefinitions:
        -
          Name: "fargate-web-app"
          Image: "fargate-demo2"
