---

Resources:
  RootRole:
    Type: "AWS::IAM::Role"
    Description: A baseline IAM role for ECS Task Execution
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: "/"
      RoleName: fargateDemoEcsTaskExecutionRole
