---

Description: >
  Builds a simple Fargate environment, and defines a sample Task Definition

Parameters:

  SubnetAZ1:
    Description: Subnet for ALB in zone A
    Type: String

  SubnetAZ2:
    Description: Subnet for ALB in zone B
    Type: String

  SubnetAZ3:
    Description: Subnet for ALB in zone C
    Type: String

  RepoName:
    Description: Name for the ECR Repository
    Type: String

#  MyVpcId:
#    Description: The ID for the VPC
#    Type: AWS::EC2::VPC::Id
#    Default: vpc-72f34a17

Resources:

  FargateDemoVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: fargate-demo

  FargateDemoInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: fargate-demo

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: FargateDemoVpc
      InternetGatewayId:
        Ref: FargateDemoInternetGateway

  FargateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FargateDemoVpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: fargate-demo-public

  FargateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FargateDemoVpc
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-1b"
      Tags:
        - Key: Name
          Value: fargate-demo-public

  FargateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FargateDemoVpc
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: "us-east-1c"
      Tags:
        - Key: Name
          Value: fargate-demo-public

  FargatePublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: FargateDemoVpc
      Tags:
        - Key: Name
          Value: fargate-demo public rout table

  FargatePublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: FargateDemoInternetGateway
    Properties:
      RouteTableId:
        Ref: FargatePublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: FargateDemoInternetGateway

  FargateSubnet1RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: FargateSubnet1
      RouteTableId:
        Ref: FargatePublicRouteTable

  FargateSubnet2RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: FargateSubnet2
      RouteTableId:
        Ref: FargatePublicRouteTable

  FargateSubnet3RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: FargateSubnet3
      RouteTableId:
        Ref: FargatePublicRouteTable

  FargateDemoRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: fargate-demo

  FargateDemoCuster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fargate-demo

  MyEcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Description: A baseline IAM role for ECS Task Execution
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /
      RoleName: fargateDemoEcsTaskExecutionRole

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt MyEcsTaskExecutionRole.Arn
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 0.5GB
      ContainerDefinitions:
        - Name: fargate-demo
          Image: !Join ["", [!Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref RepoName]]
          PortMappings:
            - ContainerPort: 80

  FargateDemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Ref: FargateDemoVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  FargateDemoALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - Ref: FargateSubnet1
        - Ref: FargateSubnet2
        - Ref: FargateSubnet3
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '50'
      SecurityGroups:
        - Ref: FargateDemoSecurityGroup
